command /extra_heart:
    description: "Give an extra_heart item to the player"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        give {item::extra_heart} to player

command /set_max_health <player> <integer>:
    description: "Set a player's max health"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        set max health of arg-1 to arg-2
        # set max health of arg-1 to {maxHealth::%arg-1%}
        if arg-1's name ends with "s":
            loop 2 times:
                send action bar "%arg-1%' max health has been set to %arg-2%" to player
                wait 1 second
        else:
            loop 2 times:
                send action bar "%arg-1%'s max health has been set to %arg-2%" to player
                wait 1 second

command /set_max_health_after_death <player> <integer>:
    description: "Set a player's max health after death"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        set {maxHealthAfterDeath::%arg-1%} to arg-2
        set max health of arg-1 to {maxHealthAfterDeath::%arg-1%}
        if arg-1's name ends with "s":
            loop 2 times:
                send action bar "%arg-1%' max health after death has been set to %arg-2%" to player
                wait 1 second
        else:
            loop 2 times:
                send action bar "%arg-1%'s max health after death has been set to %arg-2%" to player
                wait 1 second

command /health_stats:
    description: "Show a player their health stats"
    trigger:
        send "Your Health Stats"
        send "Your max health is %max health of player%" to player
        send "When you die you will have %{maxHealthAfterDeath::%player%}% hearts."