command /extra_heart:
    description: "Give an extra_heart item to the player"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        give {item::extra_heart} to player

command /reset_hearts {player}:
    description: "Reste a players max healths"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        set the max health of player to 10

command /set_health <player> <integer>:
    description: "Set a players max health"
    permission: op
    permission message: "Hey, you can't do that!"
    trigger:
        set the max health of arg-1 to arg-2