on load:
    set {item::extra_heart} to knowledge book named "Extra Heart" with lore "%nl%Use this extra heart to increase your reset health value." with custom model data "extra_heart"

on rightclick:
    if player's tool is knowledge book with custom model data "extra_heart":
        add 1 to {maxHealthAfterDeath::%player%}
        set max health of player to {maxHealthAfterDeath::%player%}
        send "You're max health after death value has been increased to %{maxHealthAfterDeath::%player%}%" to player