on load:
    set {item::respawn_heart} to knowledge book named "Respawn Heart" with lore "%nl%Use this to increase your respawn hearts." with custom model data "respawn_heart"

on rightclick:
    if player's tool is knowledge book with custom model data "respawn_heart":
        if {RespawnHearts::%player%} is greater than or equal to {maxRespawnHearts}:
            play sound "block.note_block.bass" with volume 1.0 and pitch 2.4 to player
            wait 1 tick
            set player's held item to {item::respawn_heart} # needed because knowledge book disapears on use when in survival and adventure mode (default Minecraft behavour)
            loop 3 times:
                send action bar "Sorry, you've reached the maxium number of respawn hearts" to player
                wait 1 second
        else:
            add 1 to {RespawnHearts::%player%}
            play sound "block.note_block.chime" with volume 0.5 and pitch 0.9 to player
            if max health of player is less than {RespawnHearts::%player%}:
                set max health of player to {RespawnHearts::%player%}
            loop 4 times:
                send action bar "You're respawn hearts has been increased to %{RespawnHearts::%player%}%" to player
                wait 1 second