on load:
    set {item::respawn_heart} to knowledge book named "Respawn Heart" with lore "%nl%Use this to increase your respawn hearts." with custom model data "respawn_heart"

on rightclick:
    if player's tool is knowledge book with custom model data "respawn_heart":
        if {maxRespawnHearts::%player%} is greater than or equal to 15:
            give {item::extra_heart} to player # needed because knowledge book disapears on use by itself
            loop 3 times:
                send action bar "Sorry, you've reached the maxium number of respawn hearts" to player
                wait 1 second
        else:
            add 1 to {maxRespawnHearts::%player%}
            play sound "block.note_block.chime" with volume 0.5 and pitch 0.9 to player
            if max health of player is less than {maxRespawnHearts::%player%}:
                set max health of player to {maxRespawnHearts::%player%}
            loop 4 times:
                send action bar "You're respawn hearts has been increased to %{maxRespawnHearts::%player%}%" to player
                wait 1 second