function grantHeartLogic(attacker: player, victim: player):
    if max health of {_attacker} is less than {maxHearts}:
        increase max health of {_attacker} by 1
        loop 2 times:
            send action bar "You recieved 1 heart" to {_attacker}
            wait 1 second
    else:
        loop 3 times:
            send action bar "Sorry, you have reached the maxium number of hearts" to {_attacker}
            wait 1 second

on death of player:
    if {cooldown.%attacker%.%victim%} does not exist:
        set {cooldown.%attacker%.%victim%} to now
        if {showDebugMessages} is 1:
            send "&7[&cDEBUG&7] &fCreated variable and set to &9%{cooldown.%attacker%.%victim%}%" to attacker
        grantHeartLogic(attacker, victim)
        if {showDebugMessages} is 1:
            send "&7[&cDEBUG&7] &fYou received one heart because the cooldown variable between &9%attacker% &fand &9%victim% &fdid not exist" to attacker
    else:
        if {showDebugMessages} is 1:
            send "&7[&cDEBUG&7] &fCooldown variable exists and is set to &9%{cooldown.%attacker%.%victim%}%" to attacker
        if difference between {cooldown.%attacker%.%victim%} and now is less than or equal to {deathCooldownPeriod}:
            loop 5 times:
                set {_timeFromCooldownStart} to difference between {cooldown.%attacker%.%victim%} and now
                set {_timeUntilCooldownEnds} to ({deathCooldownPeriod} - {_timeFromCooldownStart})
                set {_roundedSeconds} to round((ticks of {_timeUntilCooldownEnds}) / 20)
                set {_timeUntilCooldownEnds} to "%{_roundedSeconds}% seconds" parsed as timespan

                send action bar "Please wait %{_timeUntilCooldownEnds}% until killing %victim% again to receive a Respawn Heart" to attacker
                wait 1 second
            send action bar " " to attacker # Clear the action bar to prevent it from showing a stale time
        else:
            delete {cooldown.%attacker%.%victim%}
            grantHeartLogic(attacker, victim)
            if {showDebugMessages} is 1:
                send "&7[&cDEBUG&7] &fYou received one heart because the cooldown variable between &9%attacker% &fand &9%victim% &fwas greater than %{deathCooldownPeriod}%" to attacker
            set {cooldown.%attacker%.%victim%} to now
            if {showDebugMessages} is 1:
                send "&7[&cDEBUG&7] &fCreated variable and set to &9%{cooldown.%attacker%.%victim%}%" to attacker


    set max health of victim to {RespawnHearts::%victim%}
    set {-seeActionBar::%victim%} to true

on respawn:
    if {-seeActionBar::%player%} is true:
        delete {-seeActionBar::%player%}
        loop 2 times:
            send action bar "Your hearts have been reset" to player
            wait 1 second