# Variable Setup
on load:
    set {maxRespawnHearts} to 15
    set {defaultRespawnHearts} to 10
    set {maxHearts} to 20
    set {deathCooldownPeriod} to 5 minutes
    set {showDebugMessages} to 0 # (1 equals True, 0 equals False)

on first join:
    set {RespawnHearts::%player%} to {defaultRespawnHearts}

on join:
    if {RespawnHearts::%player%} does not exist:
        set {RespawnHearts::%player%} to {defaultRespawnHearts}